FROM public.ecr.aws/lambda/python:3.8

# Copy function code
COPY gather_data.py ${LAMBDA_TASK_ROOT}
COPY config.py ${LAMBDA_TASK_ROOT}
COPY credentials.txt ${LAMBDA_TASK_ROOT}


# Install the function's dependencies using file requirements.txt
# from your project folder.

COPY requirements.txt  .
RUN  pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "gather_data.handler" ]